# Generated by Django 5.1.3 on 2025-01-17 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optiongroup',
            name='product',
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='products',
            field=models.ManyToManyField(related_name='option_groups', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
